<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([
        	['name' => 'Bangued', 'province_id' => 1],
			['name' => 'Boliney', 'province_id' => 1],
			['name' => 'Bucay', 'province_id' => 1],
			['name' => 'Bucloc', 'province_id' => 1],
			['name' => 'Daguioman', 'province_id' => 1],
			['name' => 'Danglas', 'province_id' => 1],
			['name' => 'Dolores', 'province_id' => 1],
			['name' => 'La Paz', 'province_id' => 1],
			['name' => 'Lacub', 'province_id' => 1],
			['name' => 'Lagangilang', 'province_id' => 1],
			['name' => 'Lagayan', 'province_id' => 1],
			['name' => 'Langiden', 'province_id' => 1],
			['name' => 'Licuan-Baay', 'province_id' => 1],
			['name' => 'Luba', 'province_id' => 1],
			['name' => 'Malibcong', 'province_id' => 1],
			['name' => 'Manabo', 'province_id' => 1],
			['name' => 'Peñarrubia', 'province_id' => 1],
			['name' => 'Pidigan', 'province_id' => 1],
			['name' => 'Pilar', 'province_id' => 1],
			['name' => 'Sallapadan', 'province_id' => 1],
			['name' => 'San Isidro', 'province_id' => 1],
			['name' => 'San Juan', 'province_id' => 1],
			['name' => 'San Quintin', 'province_id' => 1],
			['name' => 'Tayum', 'province_id' => 1],
			['name' => 'Tineg', 'province_id' => 1],
			['name' => 'Tubo', 'province_id' => 1],
			['name' => 'Villaviciosa', 'province_id' => 1],
			['name' => 'Butuan City', 'province_id' => 2],
			['name' => 'Buenavista', 'province_id' => 2],
			['name' => 'Cabadbaran', 'province_id' => 2],
			['name' => 'Carmen', 'province_id' => 2],
			['name' => 'Jabonga', 'province_id' => 2],
			['name' => 'Kitcharao', 'province_id' => 2],
			['name' => 'Las Nieves', 'province_id' => 2],
			['name' => 'Magallanes', 'province_id' => 2],
			['name' => 'Nasipit', 'province_id' => 2],
			['name' => 'Remedios T. Romualdez', 'province_id' => 2],
			['name' => 'Santiago', 'province_id' => 2],
			['name' => 'Tubay', 'province_id' => 2],
			['name' => 'Bayugan', 'province_id' => 3],
			['name' => 'Bunawan', 'province_id' => 3],
			['name' => 'Esperanza', 'province_id' => 3],
			['name' => 'La Paz', 'province_id' => 3],
			['name' => 'Loreto', 'province_id' => 3],
			['name' => 'Prosperidad', 'province_id' => 3],
			['name' => 'Rosario', 'province_id' => 3],
			['name' => 'San Francisco', 'province_id' => 3],
			['name' => 'San Luis', 'province_id' => 3],
			['name' => 'Santa Josefa', 'province_id' => 3],
			['name' => 'Sibagat', 'province_id' => 3],
			['name' => 'Talacogon', 'province_id' => 3],
			['name' => 'Trento', 'province_id' => 3],
			['name' => 'Veruela', 'province_id' => 3],
			['name' => 'Altavas', 'province_id' => 4],
			['name' => 'Balete', 'province_id' => 4],
			['name' => 'Banga', 'province_id' => 4],
			['name' => 'Batan', 'province_id' => 4],
			['name' => 'Buruanga', 'province_id' => 4],
			['name' => 'Ibajay', 'province_id' => 4],
			['name' => 'Kalibo', 'province_id' => 4],
			['name' => 'Lezo', 'province_id' => 4],
			['name' => 'Libacao', 'province_id' => 4],
			['name' => 'Madalag', 'province_id' => 4],
			['name' => 'Makato', 'province_id' => 4],
			['name' => 'Malay', 'province_id' => 4],
			['name' => 'Malinao', 'province_id' => 4],
			['name' => 'Nabas', 'province_id' => 4],
			['name' => 'New Washington', 'province_id' => 4],
			['name' => 'Numancia', 'province_id' => 4],
			['name' => 'Tangalan', 'province_id' => 4],
			['name' => 'Legazpi City', 'province_id' => 5],
			['name' => 'Ligao City', 'province_id' => 5],
			['name' => 'Tabaco City', 'province_id' => 5],
			['name' => 'Bacacay', 'province_id' => 5],
			['name' => 'Camalig', 'province_id' => 5],
			['name' => 'Daraga', 'province_id' => 5],
			['name' => 'Guinobatan', 'province_id' => 5],
			['name' => 'Jovellar', 'province_id' => 5],
			['name' => 'Libon', 'province_id' => 5],
			['name' => 'Malilipot', 'province_id' => 5],
			['name' => 'Malinao', 'province_id' => 5],
			['name' => 'Manito', 'province_id' => 5],
			['name' => 'Oas', 'province_id' => 5],
			['name' => 'Pio Duran', 'province_id' => 5],
			['name' => 'Polangui', 'province_id' => 5],
			['name' => 'Rapu-Rapu', 'province_id' => 5],
			['name' => 'Santo Domingo', 'province_id' => 5],
			['name' => 'Tiwi', 'province_id' => 5],
			['name' => 'Anini-y', 'province_id' => 6],
			['name' => 'Barbaza', 'province_id' => 6],
			['name' => 'Belison', 'province_id' => 6],
			['name' => 'Bugasong', 'province_id' => 6],
			['name' => 'Caluya', 'province_id' => 6],
			['name' => 'Culasi', 'province_id' => 6],
			['name' => 'Hamtic', 'province_id' => 6],
			['name' => 'Laua-an', 'province_id' => 6],
			['name' => 'Libertad', 'province_id' => 6],
			['name' => 'Pandan', 'province_id' => 6],
			['name' => 'Patnongon', 'province_id' => 6],
			['name' => 'San Jose', 'province_id' => 6],
			['name' => 'San Remigio', 'province_id' => 6],
			['name' => 'Sebaste', 'province_id' => 6],
			['name' => 'Sibalom', 'province_id' => 6],
			['name' => 'Tibiao', 'province_id' => 6],
			['name' => 'Tobias Fornier', 'province_id' => 6],
			['name' => 'Valderrama', 'province_id' => 6],
			['name' => 'Calanasan', 'province_id' => 7],
			['name' => 'Conner', 'province_id' => 7],
			['name' => 'Flora', 'province_id' => 7],
			['name' => 'Kabugao', 'province_id' => 7],
			['name' => 'Luna', 'province_id' => 7],
			['name' => 'Pudtol', 'province_id' => 7],
			['name' => 'Santa Marcela', 'province_id' => 7],
			['name' => 'Baler', 'province_id' => 8],
			['name' => 'Casiguran', 'province_id' => 8],
			['name' => 'Dilasag', 'province_id' => 8],
			['name' => 'Dinalungan', 'province_id' => 8],
			['name' => 'Dingalan', 'province_id' => 8],
			['name' => 'Dipaculao', 'province_id' => 8],
			['name' => 'Maria Aurora', 'province_id' => 8],
			['name' => 'San Luis', 'province_id' => 8],
			['name' => 'Isabela City', 'province_id' => 9],
			['name' => 'Akbar', 'province_id' => 9],
			['name' => 'Al-Barka', 'province_id' => 9],
			['name' => 'Hadji Mohammad Ajul', 'province_id' => 9],
			['name' => 'Hadji Muhtamad', 'province_id' => 9],
			['name' => 'Lamitan', 'province_id' => 9],
			['name' => 'Lantawan', 'province_id' => 9],
			['name' => 'Maluso', 'province_id' => 9],
			['name' => 'Sumisip', 'province_id' => 9],
			['name' => 'Tabuan-Lasa', 'province_id' => 9],
			['name' => 'Tipo-Tipo', 'province_id' => 9],
			['name' => 'Tuburan', 'province_id' => 9],
			['name' => 'Ungkaya Pukan', 'province_id' => 9],
			['name' => 'Balanga City', 'province_id' => 10],
			['name' => 'Abucay', 'province_id' => 10],
			['name' => 'Bagac', 'province_id' => 10],
			['name' => 'Dinalupihan', 'province_id' => 10],
			['name' => 'Hermosa', 'province_id' => 10],
			['name' => 'Limay', 'province_id' => 10],
			['name' => 'Mariveles', 'province_id' => 10],
			['name' => 'Morong', 'province_id' => 10],
			['name' => 'Orani', 'province_id' => 10],
			['name' => 'Orion', 'province_id' => 10],
			['name' => 'Pilar', 'province_id' => 10],
			['name' => 'Samal', 'province_id' => 10],
			['name' => 'Basco', 'province_id' => 11],
			['name' => 'Itbayat', 'province_id' => 11],
			['name' => 'Ivana', 'province_id' => 11],
			['name' => 'Mahatao', 'province_id' => 11],
			['name' => 'Sabtang', 'province_id' => 11],
			['name' => 'Uyugan', 'province_id' => 11],
			['name' => 'Batangas City', 'province_id' => 12],
			['name' => 'Lipa City', 'province_id' => 12],
			['name' => 'Tanauan City', 'province_id' => 12],
			['name' => 'Agoncillo', 'province_id' => 12],
			['name' => 'Alitagtag', 'province_id' => 12],
			['name' => 'Balayan', 'province_id' => 12],
			['name' => 'Balete', 'province_id' => 12],
			['name' => 'Bauan', 'province_id' => 12],
			['name' => 'Calaca', 'province_id' => 12],
			['name' => 'Calatagan', 'province_id' => 12],
			['name' => 'Cuenca', 'province_id' => 12],
			['name' => 'Ibaan', 'province_id' => 12],
			['name' => 'Laurel', 'province_id' => 12],
			['name' => 'Lemery', 'province_id' => 12],
			['name' => 'Lian', 'province_id' => 12],
			['name' => 'Lobo', 'province_id' => 12],
			['name' => 'Mabini', 'province_id' => 12],
			['name' => 'Malvar', 'province_id' => 12],
			['name' => 'Mataas na Kahoy', 'province_id' => 12],
			['name' => 'Nasugbu', 'province_id' => 12],
			['name' => 'Padre Garcia', 'province_id' => 12],
			['name' => 'Rosario', 'province_id' => 12],
			['name' => 'San Jose', 'province_id' => 12],
			['name' => 'San Juan', 'province_id' => 12],
			['name' => 'San Luis', 'province_id' => 12],
			['name' => 'San Nicolas', 'province_id' => 12],
			['name' => 'San Pascual', 'province_id' => 12],
			['name' => 'Santa Teresita', 'province_id' => 12],
			['name' => 'Santo Tomas', 'province_id' => 12],
			['name' => 'Taal', 'province_id' => 12],
			['name' => 'Talisay', 'province_id' => 12],
			['name' => 'Taysan', 'province_id' => 12],
			['name' => 'Tingloy', 'province_id' => 12],
			['name' => 'Tuy', 'province_id' => 12],
			['name' => 'Baguio City', 'province_id' => 13],
			['name' => 'Atok', 'province_id' => 13],
			['name' => 'Bakun', 'province_id' => 13],
			['name' => 'Bokod', 'province_id' => 13],
			['name' => 'Buguias', 'province_id' => 13],
			['name' => 'Itogon', 'province_id' => 13],
			['name' => 'Kabayan', 'province_id' => 13],
			['name' => 'Kapangan', 'province_id' => 13],
			['name' => 'Kibungan', 'province_id' => 13],
			['name' => 'La Trinidad', 'province_id' => 13],
			['name' => 'Mankayan', 'province_id' => 13],
			['name' => 'Sablan', 'province_id' => 13],
			['name' => 'Tuba', 'province_id' => 13],
			['name' => 'Tublay', 'province_id' => 13],
			['name' => 'Almeria', 'province_id' => 14],
			['name' => 'Biliran', 'province_id' => 14],
			['name' => 'Cabucgayan', 'province_id' => 14],
			['name' => 'Caibiran', 'province_id' => 14],
			['name' => 'Culaba', 'province_id' => 14],
			['name' => 'Kawayan', 'province_id' => 14],
			['name' => 'Maripipi', 'province_id' => 14],
			['name' => 'Naval', 'province_id' => 14],
			['name' => 'Tagbilaran City', 'province_id' => 15],
			['name' => 'Alburquerque', 'province_id' => 15],
			['name' => 'Alicia', 'province_id' => 15],
			['name' => 'Anda', 'province_id' => 15],
			['name' => 'Antequera', 'province_id' => 15],
			['name' => 'Baclayon', 'province_id' => 15],
			['name' => 'Balilihan', 'province_id' => 15],
			['name' => 'Batuan', 'province_id' => 15],
			['name' => 'Bien Unido', 'province_id' => 15],
			['name' => 'Bilar', 'province_id' => 15],
			['name' => 'Buenavista', 'province_id' => 15],
			['name' => 'Calape', 'province_id' => 15],
			['name' => 'Candijay', 'province_id' => 15],
			['name' => 'Carmen', 'province_id' => 15],
			['name' => 'Catigbian', 'province_id' => 15],
			['name' => 'Clarin', 'province_id' => 15],
			['name' => 'Corella', 'province_id' => 15],
			['name' => 'Cortes', 'province_id' => 15],
			['name' => 'Dagohoy', 'province_id' => 15],
			['name' => 'Danao', 'province_id' => 15],
			['name' => 'Dauis', 'province_id' => 15],
			['name' => 'Dimiao', 'province_id' => 15],
			['name' => 'Duero', 'province_id' => 15],
			['name' => 'Garcia Hernandez', 'province_id' => 15],
			['name' => 'Getafe', 'province_id' => 15],
			['name' => 'Guindulman', 'province_id' => 15],
			['name' => 'Inabanga', 'province_id' => 15],
			['name' => 'Jagna', 'province_id' => 15],
			['name' => 'Lila', 'province_id' => 15],
			['name' => 'Loay', 'province_id' => 15],
			['name' => 'Loboc', 'province_id' => 15],
			['name' => 'Loon', 'province_id' => 15],
			['name' => 'Mabini', 'province_id' => 15],
			['name' => 'Maribojoc', 'province_id' => 15],
			['name' => 'Panglao', 'province_id' => 15],
			['name' => 'Pilar', 'province_id' => 15],
			['name' => 'President Carlos P. Garcia', 'province_id' => 15],
			['name' => 'Sagbayan', 'province_id' => 15],
			['name' => 'San Isidro', 'province_id' => 15],
			['name' => 'San Miguel', 'province_id' => 15],
			['name' => 'Sevilla', 'province_id' => 15],
			['name' => 'Sierra Bullones', 'province_id' => 15],
			['name' => 'Sikatuna', 'province_id' => 15],
			['name' => 'Talibon', 'province_id' => 15],
			['name' => 'Trinidad', 'province_id' => 15],
			['name' => 'Tubigon', 'province_id' => 15],
			['name' => 'Ubay', 'province_id' => 15],
			['name' => 'Valencia', 'province_id' => 15],
			['name' => 'Malaybalay City', 'province_id' => 16],
			['name' => 'Valencia City', 'province_id' => 16],
			['name' => 'Baungon', 'province_id' => 16],
			['name' => 'Cabanglasan', 'province_id' => 16],
			['name' => 'Damulog', 'province_id' => 16],
			['name' => 'Dangcagan', 'province_id' => 16],
			['name' => 'Don Carlos', 'province_id' => 16],
			['name' => 'Impasug-ong', 'province_id' => 16],
			['name' => 'Kadingilan', 'province_id' => 16],
			['name' => 'Kalilangan', 'province_id' => 16],
			['name' => 'Kibawe', 'province_id' => 16],
			['name' => 'Kitaotao', 'province_id' => 16],
			['name' => 'Lantapan', 'province_id' => 16],
			['name' => 'Libona', 'province_id' => 16],
			['name' => 'Malitbog', 'province_id' => 16],
			['name' => 'Manolo Fortich', 'province_id' => 16],
			['name' => 'Maramag', 'province_id' => 16],
			['name' => 'Pangantucan', 'province_id' => 16],
			['name' => 'Quezon', 'province_id' => 16],
			['name' => 'San Fernando', 'province_id' => 16],
			['name' => 'Sumilao', 'province_id' => 16],
			['name' => 'Talakag', 'province_id' => 16],
			['name' => 'Malolos City', 'province_id' => 17],
			['name' => 'Meycauayan City', 'province_id' => 17],
			['name' => 'San Jose del Monte City', 'province_id' => 17],
			['name' => 'Angat', 'province_id' => 17],
			['name' => 'Balagtas', 'province_id' => 17],
			['name' => 'Baliuag', 'province_id' => 17],
			['name' => 'Bocaue', 'province_id' => 17],
			['name' => 'Bulacan', 'province_id' => 17],
			['name' => 'Bustos', 'province_id' => 17],
			['name' => 'Calumpit', 'province_id' => 17],
			['name' => 'Doña Remedios Trinidad', 'province_id' => 17],
			['name' => 'Guiguinto', 'province_id' => 17],
			['name' => 'Hagonoy', 'province_id' => 17],
			['name' => 'Marilao', 'province_id' => 17],
			['name' => 'Norzagaray', 'province_id' => 17],
			['name' => 'Obando', 'province_id' => 17],
			['name' => 'Pandi', 'province_id' => 17],
			['name' => 'Paombong', 'province_id' => 17],
			['name' => 'Plaridel', 'province_id' => 17],
			['name' => 'Pulilan', 'province_id' => 17],
			['name' => 'San Ildefonso', 'province_id' => 17],
			['name' => 'San Miguel', 'province_id' => 17],
			['name' => 'San Rafael', 'province_id' => 17],
			['name' => 'Santa Maria', 'province_id' => 17],
			['name' => 'Tuguegarao City', 'province_id' => 18],
			['name' => 'Abulug', 'province_id' => 18],
			['name' => 'Alcala', 'province_id' => 18],
			['name' => 'Allacapan', 'province_id' => 18],
			['name' => 'Amulung', 'province_id' => 18],
			['name' => 'Aparri', 'province_id' => 18],
			['name' => 'Baggao', 'province_id' => 18],
			['name' => 'Ballesteros', 'province_id' => 18],
			['name' => 'Buguey', 'province_id' => 18],
			['name' => 'Calayan', 'province_id' => 18],
			['name' => 'Camalaniugan', 'province_id' => 18],
			['name' => 'Claveria', 'province_id' => 18],
			['name' => 'Enrile', 'province_id' => 18],
			['name' => 'Gattaran', 'province_id' => 18],
			['name' => 'Gonzaga', 'province_id' => 18],
			['name' => 'Iguig', 'province_id' => 18],
			['name' => 'Lal-lo', 'province_id' => 18],
			['name' => 'Lasam', 'province_id' => 18],
			['name' => 'Pamplona', 'province_id' => 18],
			['name' => 'Peñablanca', 'province_id' => 18],
			['name' => 'Piat', 'province_id' => 18],
			['name' => 'Rizal', 'province_id' => 18],
			['name' => 'Sanchez-Mira', 'province_id' => 18],
			['name' => 'Santa Ana', 'province_id' => 18],
			['name' => 'Santa Praxedes', 'province_id' => 18],
			['name' => 'Santa Teresita', 'province_id' => 18],
			['name' => 'Santo Niño', 'province_id' => 18],
			['name' => 'Solana', 'province_id' => 18],
			['name' => 'Tuao', 'province_id' => 18],
			['name' => 'Basud', 'province_id' => 19],
			['name' => 'Capalonga', 'province_id' => 19],
			['name' => 'Daet', 'province_id' => 19],
			['name' => 'Jose Panganiban', 'province_id' => 19],
			['name' => 'Labo', 'province_id' => 19],
			['name' => 'Mercedes', 'province_id' => 19],
			['name' => 'Paracale', 'province_id' => 19],
			['name' => 'San Lorenzo Ruiz', 'province_id' => 19],
			['name' => 'San Vicente', 'province_id' => 19],
			['name' => 'Santa Elena', 'province_id' => 19],
			['name' => 'Talisay', 'province_id' => 19],
			['name' => 'Vinzons', 'province_id' => 19],
			['name' => 'Iriga City', 'province_id' => 20],
			['name' => 'Naga City', 'province_id' => 20],
			['name' => 'Baao', 'province_id' => 20],
			['name' => 'Balatan', 'province_id' => 20],
			['name' => 'Bato', 'province_id' => 20],
			['name' => 'Bombon', 'province_id' => 20],
			['name' => 'Buhi', 'province_id' => 20],
			['name' => 'Bula', 'province_id' => 20],
			['name' => 'Cabusao', 'province_id' => 20],
			['name' => 'Calabanga', 'province_id' => 20],
			['name' => 'Camaligan', 'province_id' => 20],
			['name' => 'Canaman', 'province_id' => 20],
			['name' => 'Caramoan', 'province_id' => 20],
			['name' => 'Del Gallego', 'province_id' => 20],
			['name' => 'Gainza', 'province_id' => 20],
			['name' => 'Garchitorena', 'province_id' => 20],
			['name' => 'Goa', 'province_id' => 20],
			['name' => 'Lagonoy', 'province_id' => 20],
			['name' => 'Libmanan', 'province_id' => 20],
			['name' => 'Lupi', 'province_id' => 20],
			['name' => 'Magarao', 'province_id' => 20],
			['name' => 'Milaor', 'province_id' => 20],
			['name' => 'Minalabac', 'province_id' => 20],
			['name' => 'Nabua', 'province_id' => 20],
			['name' => 'Ocampo', 'province_id' => 20],
			['name' => 'Pamplona', 'province_id' => 20],
			['name' => 'Pasacao', 'province_id' => 20],
			['name' => 'Pili', 'province_id' => 20],
			['name' => 'Presentacion', 'province_id' => 20],
			['name' => 'Ragay', 'province_id' => 20],
			['name' => 'Sagñay', 'province_id' => 20],
			['name' => 'San Fernando', 'province_id' => 20],
			['name' => 'San Jose', 'province_id' => 20],
			['name' => 'Sipocot', 'province_id' => 20],
			['name' => 'Siruma', 'province_id' => 20],
			['name' => 'Tigaon', 'province_id' => 20],
			['name' => 'Tinambac', 'province_id' => 20],
			['name' => 'Catarman', 'province_id' => 21],
			['name' => 'Guinsiliban', 'province_id' => 21],
			['name' => 'Mahinog', 'province_id' => 21],
			['name' => 'Mambajao', 'province_id' => 21],
			['name' => 'Sagay', 'province_id' => 21],
			['name' => 'Roxas City', 'province_id' => 22],
			['name' => 'Cuartero', 'province_id' => 22],
			['name' => 'Dao', 'province_id' => 22],
			['name' => 'Dumalag', 'province_id' => 22],
			['name' => 'Dumarao', 'province_id' => 22],
			['name' => 'Ivisan', 'province_id' => 22],
			['name' => 'Jamindan', 'province_id' => 22],
			['name' => 'Ma-ayon', 'province_id' => 22],
			['name' => 'Mambusao', 'province_id' => 22],
			['name' => 'Panay', 'province_id' => 22],
			['name' => 'Panitan', 'province_id' => 22],
			['name' => 'Pilar', 'province_id' => 22],
			['name' => 'Pontevedra', 'province_id' => 22],
			['name' => 'President Roxas', 'province_id' => 22],
			['name' => 'Sapi-an', 'province_id' => 22],
			['name' => 'Sigma', 'province_id' => 22],
			['name' => 'Tapaz', 'province_id' => 22],
			['name' => 'Bagamanoc', 'province_id' => 23],
			['name' => 'Baras', 'province_id' => 23],
			['name' => 'Bato', 'province_id' => 23],
			['name' => 'Caramoran', 'province_id' => 23],
			['name' => 'Gigmoto', 'province_id' => 23],
			['name' => 'Pandan', 'province_id' => 23],
			['name' => 'Panganiban', 'province_id' => 23],
			['name' => 'San Andres', 'province_id' => 23],
			['name' => 'San Miguel', 'province_id' => 23],
			['name' => 'Viga', 'province_id' => 23],
			['name' => 'Virac', 'province_id' => 23],
			['name' => 'Cavite City', 'province_id' => 24],
			['name' => 'Dasmariñas City', 'province_id' => 24],
			['name' => 'Tagaytay City', 'province_id' => 24],
			['name' => 'Trece Martires City', 'province_id' => 24],
			['name' => 'Alfonso', 'province_id' => 24],
			['name' => 'Amadeo', 'province_id' => 24],
			['name' => 'Bacoor', 'province_id' => 24],
			['name' => 'Carmona', 'province_id' => 24],
			['name' => 'General Mariano Alvarez', 'province_id' => 24],
			['name' => 'General Emilio Aguinaldo', 'province_id' => 24],
			['name' => 'General Trias', 'province_id' => 24],
			['name' => 'Imus', 'province_id' => 24],
			['name' => 'Indang', 'province_id' => 24],
			['name' => 'Kawit', 'province_id' => 24],
			['name' => 'Magallanes', 'province_id' => 24],
			['name' => 'Maragondon', 'province_id' => 24],
			['name' => 'Mendez', 'province_id' => 24],
			['name' => 'Naic', 'province_id' => 24],
			['name' => 'Noveleta', 'province_id' => 24],
			['name' => 'Rosario', 'province_id' => 24],
			['name' => 'Silang', 'province_id' => 24],
			['name' => 'Tanza', 'province_id' => 24],
			['name' => 'Ternate', 'province_id' => 24],
			['name' => 'Bogo City', 'province_id' => 25],
			['name' => 'Cebu City', 'province_id' => 25],
			['name' => 'Carcar City', 'province_id' => 25],
			['name' => 'Danao City', 'province_id' => 25],
			['name' => 'Lapu-Lapu City', 'province_id' => 25],
			['name' => 'Mandaue City', 'province_id' => 25],
			['name' => 'Naga City', 'province_id' => 25],
			['name' => 'Talisay City', 'province_id' => 25],
			['name' => 'Toledo City', 'province_id' => 25],
			['name' => 'Alcantara', 'province_id' => 25],
			['name' => 'Alcoy', 'province_id' => 25],
			['name' => 'Alegria', 'province_id' => 25],
			['name' => 'Aloguinsan', 'province_id' => 25],
			['name' => 'Argao', 'province_id' => 25],
			['name' => 'Asturias', 'province_id' => 25],
			['name' => 'Badian', 'province_id' => 25],
			['name' => 'Balamban', 'province_id' => 25],
			['name' => 'Bantayan', 'province_id' => 25],
			['name' => 'Barili', 'province_id' => 25],
			['name' => 'Boljoon', 'province_id' => 25],
			['name' => 'Borbon', 'province_id' => 25],
			['name' => 'Carmen', 'province_id' => 25],
			['name' => 'Catmon', 'province_id' => 25],
			['name' => 'Compostela', 'province_id' => 25],
			['name' => 'Consolacion', 'province_id' => 25],
			['name' => 'Cordoba', 'province_id' => 25],
			['name' => 'Daanbantayan', 'province_id' => 25],
			['name' => 'Dalaguete', 'province_id' => 25],
			['name' => 'Dumanjug', 'province_id' => 25],
			['name' => 'Ginatilan', 'province_id' => 25],
			['name' => 'Liloan', 'province_id' => 25],
			['name' => 'Madridejos', 'province_id' => 25],
			['name' => 'Malabuyoc', 'province_id' => 25],
			['name' => 'Medellin', 'province_id' => 25],
			['name' => 'Minglanilla', 'province_id' => 25],
			['name' => 'Moalboal', 'province_id' => 25],
			['name' => 'Oslob', 'province_id' => 25],
			['name' => 'Pilar', 'province_id' => 25],
			['name' => 'Pinamungahan', 'province_id' => 25],
			['name' => 'Poro', 'province_id' => 25],
			['name' => 'Ronda', 'province_id' => 25],
			['name' => 'Samboan', 'province_id' => 25],
			['name' => 'San Fernando', 'province_id' => 25],
			['name' => 'San Francisco', 'province_id' => 25],
			['name' => 'San Remigio', 'province_id' => 25],
			['name' => 'Santa Fe', 'province_id' => 25],
			['name' => 'Santander', 'province_id' => 25],
			['name' => 'Sibonga', 'province_id' => 25],
			['name' => 'Sogod', 'province_id' => 25],
			['name' => 'Tabogon', 'province_id' => 25],
			['name' => 'Tabuelan', 'province_id' => 25],
			['name' => 'Tuburan', 'province_id' => 25],
			['name' => 'Tudela', 'province_id' => 25],
			['name' => 'Compostela', 'province_id' => 26],
			['name' => 'Laak', 'province_id' => 26],
			['name' => 'Mabini', 'province_id' => 26],
			['name' => 'Maco', 'province_id' => 26],
			['name' => 'Maragusan', 'province_id' => 26],
			['name' => 'Mawab', 'province_id' => 26],
			['name' => 'Monkayo', 'province_id' => 26],
			['name' => 'Montevista', 'province_id' => 26],
			['name' => 'Nabunturan', 'province_id' => 26],
			['name' => 'New Bataan', 'province_id' => 26],
			['name' => 'Pantukan', 'province_id' => 26],
			['name' => 'Kidapawan City', 'province_id' => 27],
			['name' => 'Alamada', 'province_id' => 27],
			['name' => 'Aleosan', 'province_id' => 27],
			['name' => 'Antipas', 'province_id' => 27],
			['name' => 'Arakan', 'province_id' => 27],
			['name' => 'Banisilan', 'province_id' => 27],
			['name' => 'Carmen', 'province_id' => 27],
			['name' => 'Kabacan', 'province_id' => 27],
			['name' => 'Libungan', 'province_id' => 27],
			['name' => 'M\'lang', 'province_id' => 27],
			['name' => 'Magpet', 'province_id' => 27],
			['name' => 'Makilala', 'province_id' => 27],
			['name' => 'Matalam', 'province_id' => 27],
			['name' => 'Midsayap', 'province_id' => 27],
			['name' => 'Pigkawayan', 'province_id' => 27],
			['name' => 'Pikit', 'province_id' => 27],
			['name' => 'President Roxas', 'province_id' => 27],
			['name' => 'Tulunan', 'province_id' => 27],
			['name' => 'Panabo City', 'province_id' => 28],
			['name' => 'Island Garden City of Samal', 'province_id' => 28],
			['name' => 'Tagum City', 'province_id' => 28],
			['name' => 'Asuncion', 'province_id' => 28],
			['name' => 'Braulio E. Dujali', 'province_id' => 28],
			['name' => 'Carmen', 'province_id' => 28],
			['name' => 'Kapalong', 'province_id' => 28],
			['name' => 'New Corella', 'province_id' => 28],
			['name' => 'San Isidro', 'province_id' => 28],
			['name' => 'Santo Tomas', 'province_id' => 28],
			['name' => 'Talaingod', 'province_id' => 28],
			['name' => 'Davao City', 'province_id' => 29],
			['name' => 'Digos City', 'province_id' => 29],
			['name' => 'Bansalan', 'province_id' => 29],
			['name' => 'Don Marcelino', 'province_id' => 29],
			['name' => 'Hagonoy', 'province_id' => 29],
			['name' => 'Jose Abad Santos', 'province_id' => 29],
			['name' => 'Kiblawan', 'province_id' => 29],
			['name' => 'Magsaysay', 'province_id' => 29],
			['name' => 'Malalag', 'province_id' => 29],
			['name' => 'Malita', 'province_id' => 29],
			['name' => 'Matanao', 'province_id' => 29],
			['name' => 'Padada', 'province_id' => 29],
			['name' => 'Santa Cruz', 'province_id' => 29],
			['name' => 'Santa Maria', 'province_id' => 29],
			['name' => 'Sarangani', 'province_id' => 29],
			['name' => 'Sulop', 'province_id' => 29],
			['name' => 'Mati City', 'province_id' => 30],
			['name' => 'Baganga', 'province_id' => 30],
			['name' => 'Banaybanay', 'province_id' => 30],
			['name' => 'Boston', 'province_id' => 30],
			['name' => 'Caraga', 'province_id' => 30],
			['name' => 'Cateel', 'province_id' => 30],
			['name' => 'Governor Generoso', 'province_id' => 30],
			['name' => 'Lupon', 'province_id' => 30],
			['name' => 'Manay', 'province_id' => 30],
			['name' => 'San Isidro', 'province_id' => 30],
			['name' => 'Tarragona', 'province_id' => 30],
			['name' => 'Arteche', 'province_id' => 31],
			['name' => 'Balangiga', 'province_id' => 31],
			['name' => 'Balangkayan', 'province_id' => 31],
			['name' => 'Borongan', 'province_id' => 31],
			['name' => 'Can-avid', 'province_id' => 31],
			['name' => 'Dolores', 'province_id' => 31],
			['name' => 'General MacArthur', 'province_id' => 31],
			['name' => 'Giporlos', 'province_id' => 31],
			['name' => 'Guiuan', 'province_id' => 31],
			['name' => 'Hernani', 'province_id' => 31],
			['name' => 'Jipapad', 'province_id' => 31],
			['name' => 'Lawaan', 'province_id' => 31],
			['name' => 'Llorente', 'province_id' => 31],
			['name' => 'Maslog', 'province_id' => 31],
			['name' => 'Maydolong', 'province_id' => 31],
			['name' => 'Mercedes', 'province_id' => 31],
			['name' => 'Oras', 'province_id' => 31],
			['name' => 'Quinapondan', 'province_id' => 31],
			['name' => 'Salcedo', 'province_id' => 31],
			['name' => 'San Julian', 'province_id' => 31],
			['name' => 'San Policarpo', 'province_id' => 31],
			['name' => 'Sulat', 'province_id' => 31],
			['name' => 'Taft', 'province_id' => 31],
			['name' => 'Buenavista', 'province_id' => 32],
			['name' => 'Jordan', 'province_id' => 32],
			['name' => 'Nueva Valencia', 'province_id' => 32],
			['name' => 'San Lorenzo', 'province_id' => 32],
			['name' => 'Sibunag', 'province_id' => 32],
			['name' => 'Aguinaldo', 'province_id' => 33],
			['name' => 'Alfonso Lista', 'province_id' => 33],
			['name' => 'Asipulo', 'province_id' => 33],
			['name' => 'Banaue', 'province_id' => 33],
			['name' => 'Hingyon', 'province_id' => 33],
			['name' => 'Hungduan', 'province_id' => 33],
			['name' => 'Kiangan', 'province_id' => 33],
			['name' => 'Lagawe', 'province_id' => 33],
			['name' => 'Lamut', 'province_id' => 33],
			['name' => 'Mayoyao', 'province_id' => 33],
			['name' => 'Tinoc', 'province_id' => 33],
			['name' => 'Batac City', 'province_id' => 34],
			['name' => 'Laoag City', 'province_id' => 34],
			['name' => 'Adams', 'province_id' => 34],
			['name' => 'Bacarra', 'province_id' => 34],
			['name' => 'Badoc', 'province_id' => 34],
			['name' => 'Bangui', 'province_id' => 34],
			['name' => 'Banna', 'province_id' => 34],
			['name' => 'Burgos', 'province_id' => 34],
			['name' => 'Carasi', 'province_id' => 34],
			['name' => 'Currimao', 'province_id' => 34],
			['name' => 'Dingras', 'province_id' => 34],
			['name' => 'Dumalneg', 'province_id' => 34],
			['name' => 'Marcos', 'province_id' => 34],
			['name' => 'Nueva Era', 'province_id' => 34],
			['name' => 'Pagudpud', 'province_id' => 34],
			['name' => 'Paoay', 'province_id' => 34],
			['name' => 'Pasuquin', 'province_id' => 34],
			['name' => 'Piddig', 'province_id' => 34],
			['name' => 'Pinili', 'province_id' => 34],
			['name' => 'San Nicolas', 'province_id' => 34],
			['name' => 'Sarrat', 'province_id' => 34],
			['name' => 'Solsona', 'province_id' => 34],
			['name' => 'Vintar', 'province_id' => 34],
			['name' => 'Candon City', 'province_id' => 35],
			['name' => 'Vigan City', 'province_id' => 35],
			['name' => 'Alilem', 'province_id' => 35],
			['name' => 'Banayoyo', 'province_id' => 35],
			['name' => 'Bantay', 'province_id' => 35],
			['name' => 'Burgos', 'province_id' => 35],
			['name' => 'Cabugao', 'province_id' => 35],
			['name' => 'Caoayan', 'province_id' => 35],
			['name' => 'Cervantes', 'province_id' => 35],
			['name' => 'Galimuyod', 'province_id' => 35],
			['name' => 'Gregorio Del Pilar', 'province_id' => 35],
			['name' => 'Lidlidda', 'province_id' => 35],
			['name' => 'Magsingal', 'province_id' => 35],
			['name' => 'Nagbukel', 'province_id' => 35],
			['name' => 'Narvacan', 'province_id' => 35],
			['name' => 'Quirino', 'province_id' => 35],
			['name' => 'Salcedo', 'province_id' => 35],
			['name' => 'San Emilio', 'province_id' => 35],
			['name' => 'San Esteban', 'province_id' => 35],
			['name' => 'San Ildefonso', 'province_id' => 35],
			['name' => 'San Juan', 'province_id' => 35],
			['name' => 'San Vicente', 'province_id' => 35],
			['name' => 'Santa', 'province_id' => 35],
			['name' => 'Santa Catalina', 'province_id' => 35],
			['name' => 'Santa Cruz', 'province_id' => 35],
			['name' => 'Santa Lucia', 'province_id' => 35],
			['name' => 'Santa Maria', 'province_id' => 35],
			['name' => 'Santiago', 'province_id' => 35],
			['name' => 'Santo Domingo', 'province_id' => 35],
			['name' => 'Sigay', 'province_id' => 35],
			['name' => 'Sinait', 'province_id' => 35],
			['name' => 'Sugpon', 'province_id' => 35],
			['name' => 'Suyo', 'province_id' => 35],
			['name' => 'Tagudin', 'province_id' => 35],
			['name' => 'Iloilo City', 'province_id' => 36],
			['name' => 'Passi City', 'province_id' => 36],
			['name' => 'Ajuy', 'province_id' => 36],
			['name' => 'Alimodian', 'province_id' => 36],
			['name' => 'Anilao', 'province_id' => 36],
			['name' => 'Badiangan', 'province_id' => 36],
			['name' => 'Balasan', 'province_id' => 36],
			['name' => 'Banate', 'province_id' => 36],
			['name' => 'Barotac Nuevo', 'province_id' => 36],
			['name' => 'Barotac Viejo', 'province_id' => 36],
			['name' => 'Batad', 'province_id' => 36],
			['name' => 'Bingawan', 'province_id' => 36],
			['name' => 'Cabatuan', 'province_id' => 36],
			['name' => 'Calinog', 'province_id' => 36],
			['name' => 'Carles', 'province_id' => 36],
			['name' => 'Concepcion', 'province_id' => 36],
			['name' => 'Dingle', 'province_id' => 36],
			['name' => 'Dueñas', 'province_id' => 36],
			['name' => 'Dumangas', 'province_id' => 36],
			['name' => 'Estancia', 'province_id' => 36],
			['name' => 'Guimbal', 'province_id' => 36],
			['name' => 'Igbaras', 'province_id' => 36],
			['name' => 'Janiuay', 'province_id' => 36],
			['name' => 'Lambunao', 'province_id' => 36],
			['name' => 'Leganes', 'province_id' => 36],
			['name' => 'Lemery', 'province_id' => 36],
			['name' => 'Leon', 'province_id' => 36],
			['name' => 'Maasin', 'province_id' => 36],
			['name' => 'Miagao', 'province_id' => 36],
			['name' => 'Mina', 'province_id' => 36],
			['name' => 'New Lucena', 'province_id' => 36],
			['name' => 'Oton', 'province_id' => 36],
			['name' => 'Pavia', 'province_id' => 36],
			['name' => 'Pototan', 'province_id' => 36],
			['name' => 'San Dionisio', 'province_id' => 36],
			['name' => 'San Enrique', 'province_id' => 36],
			['name' => 'San Joaquin', 'province_id' => 36],
			['name' => 'San Miguel', 'province_id' => 36],
			['name' => 'San Rafael', 'province_id' => 36],
			['name' => 'Santa Barbara', 'province_id' => 36],
			['name' => 'Sara', 'province_id' => 36],
			['name' => 'Tigbauan', 'province_id' => 36],
			['name' => 'Tubungan', 'province_id' => 36],
			['name' => 'Zarraga', 'province_id' => 36],
			['name' => 'Cauayan City', 'province_id' => 37],
			['name' => 'Santiago City', 'province_id' => 37],
			['name' => 'Alicia', 'province_id' => 37],
			['name' => 'Angadanan', 'province_id' => 37],
			['name' => 'Aurora', 'province_id' => 37],
			['name' => 'Benito Soliven', 'province_id' => 37],
			['name' => 'Burgos', 'province_id' => 37],
			['name' => 'Cabagan', 'province_id' => 37],
			['name' => 'Cabatuan', 'province_id' => 37],
			['name' => 'Cordon', 'province_id' => 37],
			['name' => 'Delfin Albano', 'province_id' => 37],
			['name' => 'Dinapigue', 'province_id' => 37],
			['name' => 'Divilacan', 'province_id' => 37],
			['name' => 'Echague', 'province_id' => 37],
			['name' => 'Gamu', 'province_id' => 37],
			['name' => 'Ilagan', 'province_id' => 37],
			['name' => 'Jones', 'province_id' => 37],
			['name' => 'Luna', 'province_id' => 37],
			['name' => 'Maconacon', 'province_id' => 37],
			['name' => 'Mallig', 'province_id' => 37],
			['name' => 'Naguilian', 'province_id' => 37],
			['name' => 'Palanan', 'province_id' => 37],
			['name' => 'Quezon', 'province_id' => 37],
			['name' => 'Quirino', 'province_id' => 37],
			['name' => 'Ramon', 'province_id' => 37],
			['name' => 'Reina Mercedes', 'province_id' => 37],
			['name' => 'Roxas', 'province_id' => 37],
			['name' => 'San Agustin', 'province_id' => 37],
			['name' => 'San Guillermo', 'province_id' => 37],
			['name' => 'San Isidro', 'province_id' => 37],
			['name' => 'San Manuel', 'province_id' => 37],
			['name' => 'San Mariano', 'province_id' => 37],
			['name' => 'San Mateo', 'province_id' => 37],
			['name' => 'San Pablo', 'province_id' => 37],
			['name' => 'Santa Maria', 'province_id' => 37],
			['name' => 'Santo Tomas', 'province_id' => 37],
			['name' => 'Tumauini', 'province_id' => 37],
			['name' => 'Tabuk', 'province_id' => 38],
			['name' => 'Balbalan', 'province_id' => 38],
			['name' => 'Lubuagan', 'province_id' => 38],
			['name' => 'Pasil', 'province_id' => 38],
			['name' => 'Pinukpuk', 'province_id' => 38],
			['name' => 'Rizal', 'province_id' => 38],
			['name' => 'Tanudan', 'province_id' => 38],
			['name' => 'Tinglayan', 'province_id' => 38],
			['name' => 'San Fernando City', 'province_id' => 39],
			['name' => 'Agoo', 'province_id' => 39],
			['name' => 'Aringay', 'province_id' => 39],
			['name' => 'Bacnotan', 'province_id' => 39],
			['name' => 'Bagulin', 'province_id' => 39],
			['name' => 'Balaoan', 'province_id' => 39],
			['name' => 'Bangar', 'province_id' => 39],
			['name' => 'Bauang', 'province_id' => 39],
			['name' => 'Burgos', 'province_id' => 39],
			['name' => 'Caba', 'province_id' => 39],
			['name' => 'Luna', 'province_id' => 39],
			['name' => 'Naguilian', 'province_id' => 39],
			['name' => 'Pugo', 'province_id' => 39],
			['name' => 'Rosario', 'province_id' => 39],
			['name' => 'San Gabriel', 'province_id' => 39],
			['name' => 'San Juan', 'province_id' => 39],
			['name' => 'Santo Tomas', 'province_id' => 39],
			['name' => 'Santol', 'province_id' => 39],
			['name' => 'Sudipen', 'province_id' => 39],
			['name' => 'Tubao', 'province_id' => 39],
			['name' => 'Biñan City', 'province_id' => 40],
			['name' => 'Calamba City', 'province_id' => 40],
			['name' => 'San Pablo City', 'province_id' => 40],
			['name' => 'Santa Rosa City', 'province_id' => 40],
			['name' => 'Alaminos', 'province_id' => 40],
			['name' => 'Bay', 'province_id' => 40],
			['name' => 'Cabuyao', 'province_id' => 40],
			['name' => 'Calauan', 'province_id' => 40],
			['name' => 'Cavinti', 'province_id' => 40],
			['name' => 'Famy', 'province_id' => 40],
			['name' => 'Kalayaan', 'province_id' => 40],
			['name' => 'Liliw', 'province_id' => 40],
			['name' => 'Los Baños', 'province_id' => 40],
			['name' => 'Luisiana', 'province_id' => 40],
			['name' => 'Lumban', 'province_id' => 40],
			['name' => 'Mabitac', 'province_id' => 40],
			['name' => 'Magdalena', 'province_id' => 40],
			['name' => 'Majayjay', 'province_id' => 40],
			['name' => 'Nagcarlan', 'province_id' => 40],
			['name' => 'Paete', 'province_id' => 40],
			['name' => 'Pagsanjan', 'province_id' => 40],
			['name' => 'Pakil', 'province_id' => 40],
			['name' => 'Pangil', 'province_id' => 40],
			['name' => 'Pila', 'province_id' => 40],
			['name' => 'Rizal', 'province_id' => 40],
			['name' => 'San Pedro', 'province_id' => 40],
			['name' => 'Santa Cruz', 'province_id' => 40],
			['name' => 'Santa Maria', 'province_id' => 40],
			['name' => 'Siniloan', 'province_id' => 40],
			['name' => 'Victoria', 'province_id' => 40],
			['name' => 'Iligan City', 'province_id' => 41],
			['name' => 'Bacolod', 'province_id' => 41],
			['name' => 'Baloi', 'province_id' => 41],
			['name' => 'Baroy', 'province_id' => 41],
			['name' => 'Kapatagan', 'province_id' => 41],
			['name' => 'Kauswagan', 'province_id' => 41],
			['name' => 'Kolambugan', 'province_id' => 41],
			['name' => 'Lala', 'province_id' => 41],
			['name' => 'Linamon', 'province_id' => 41],
			['name' => 'Magsaysay', 'province_id' => 41],
			['name' => 'Maigo', 'province_id' => 41],
			['name' => 'Matungao', 'province_id' => 41],
			['name' => 'Munai', 'province_id' => 41],
			['name' => 'Nunungan', 'province_id' => 41],
			['name' => 'Pantao Ragat', 'province_id' => 41],
			['name' => 'Pantar', 'province_id' => 41],
			['name' => 'Poona Piagapo', 'province_id' => 41],
			['name' => 'Salvador', 'province_id' => 41],
			['name' => 'Sapad', 'province_id' => 41],
			['name' => 'Sultan Naga Dimaporo', 'province_id' => 41],
			['name' => 'Tagoloan', 'province_id' => 41],
			['name' => 'Tangcal', 'province_id' => 41],
			['name' => 'Tubod', 'province_id' => 41],
			['name' => 'Marawi City', 'province_id' => 42],
			['name' => 'Bacolod-Kalawi', 'province_id' => 42],
			['name' => 'Balabagan', 'province_id' => 42],
			['name' => 'Balindong', 'province_id' => 42],
			['name' => 'Bayang', 'province_id' => 42],
			['name' => 'Binidayan', 'province_id' => 42],
			['name' => 'Buadiposo-Buntong', 'province_id' => 42],
			['name' => 'Bubong', 'province_id' => 42],
			['name' => 'Bumbaran', 'province_id' => 42],
			['name' => 'Butig', 'province_id' => 42],
			['name' => 'Calanogas', 'province_id' => 42],
			['name' => 'Ditsaan-Ramain', 'province_id' => 42],
			['name' => 'Ganassi', 'province_id' => 42],
			['name' => 'Kapai', 'province_id' => 42],
			['name' => 'Kapatagan', 'province_id' => 42],
			['name' => 'Lumba-Bayabao', 'province_id' => 42],
			['name' => 'Lumbaca-Unayan', 'province_id' => 42],
			['name' => 'Lumbatan', 'province_id' => 42],
			['name' => 'Lumbayanague', 'province_id' => 42],
			['name' => 'Madalum', 'province_id' => 42],
			['name' => 'Madamba', 'province_id' => 42],
			['name' => 'Maguing', 'province_id' => 42],
			['name' => 'Malabang', 'province_id' => 42],
			['name' => 'Marantao', 'province_id' => 42],
			['name' => 'Marogong', 'province_id' => 42],
			['name' => 'Masiu', 'province_id' => 42],
			['name' => 'Mulondo', 'province_id' => 42],
			['name' => 'Pagayawan', 'province_id' => 42],
			['name' => 'Piagapo', 'province_id' => 42],
			['name' => 'Poona Bayabao', 'province_id' => 42],
			['name' => 'Pualas', 'province_id' => 42],
			['name' => 'Saguiaran', 'province_id' => 42],
			['name' => 'Sultan Dumalondong', 'province_id' => 42],
			['name' => 'Picong', 'province_id' => 42],
			['name' => 'Tagoloan II', 'province_id' => 42],
			['name' => 'Tamparan', 'province_id' => 42],
			['name' => 'Taraka', 'province_id' => 42],
			['name' => 'Tubaran', 'province_id' => 42],
			['name' => 'Tugaya', 'province_id' => 42],
			['name' => 'Wao', 'province_id' => 42],
			['name' => 'Ormoc City', 'province_id' => 43],
			['name' => 'Tacloban City', 'province_id' => 43],
			['name' => 'Abuyog', 'province_id' => 43],
			['name' => 'Alangalang', 'province_id' => 43],
			['name' => 'Albuera', 'province_id' => 43],
			['name' => 'Babatngon', 'province_id' => 43],
			['name' => 'Barugo', 'province_id' => 43],
			['name' => 'Bato', 'province_id' => 43],
			['name' => 'Baybay', 'province_id' => 43],
			['name' => 'Burauen', 'province_id' => 43],
			['name' => 'Calubian', 'province_id' => 43],
			['name' => 'Capoocan', 'province_id' => 43],
			['name' => 'Carigara', 'province_id' => 43],
			['name' => 'Dagami', 'province_id' => 43],
			['name' => 'Dulag', 'province_id' => 43],
			['name' => 'Hilongos', 'province_id' => 43],
			['name' => 'Hindang', 'province_id' => 43],
			['name' => 'Inopacan', 'province_id' => 43],
			['name' => 'Isabel', 'province_id' => 43],
			['name' => 'Jaro', 'province_id' => 43],
			['name' => 'Javier', 'province_id' => 43],
			['name' => 'Julita', 'province_id' => 43],
			['name' => 'Kananga', 'province_id' => 43],
			['name' => 'La Paz', 'province_id' => 43],
			['name' => 'Leyte', 'province_id' => 43],
			['name' => 'Liloan', 'province_id' => 43],
			['name' => 'MacArthur', 'province_id' => 43],
			['name' => 'Mahaplag', 'province_id' => 43],
			['name' => 'Matag-ob', 'province_id' => 43],
			['name' => 'Matalom', 'province_id' => 43],
			['name' => 'Mayorga', 'province_id' => 43],
			['name' => 'Merida', 'province_id' => 43],
			['name' => 'Palo', 'province_id' => 43],
			['name' => 'Palompon', 'province_id' => 43],
			['name' => 'Pastrana', 'province_id' => 43],
			['name' => 'San Isidro', 'province_id' => 43],
			['name' => 'San Miguel', 'province_id' => 43],
			['name' => 'Santa Fe', 'province_id' => 43],
			['name' => 'Sogod', 'province_id' => 43],
			['name' => 'Tabango', 'province_id' => 43],
			['name' => 'Tabontabon', 'province_id' => 43],
			['name' => 'Tanauan', 'province_id' => 43],
			['name' => 'Tolosa', 'province_id' => 43],
			['name' => 'Tunga', 'province_id' => 43],
			['name' => 'Villaba', 'province_id' => 43],
			['name' => 'Cotabato City', 'province_id' => 44],
			['name' => 'Ampatuan', 'province_id' => 44],
			['name' => 'Barira', 'province_id' => 44],
			['name' => 'Buldon', 'province_id' => 44],
			['name' => 'Buluan', 'province_id' => 44],
			['name' => 'Datu Abdullah Sangki', 'province_id' => 44],
			['name' => 'Datu Anggal Midtimbang', 'province_id' => 44],
			['name' => 'Datu Blah T. Sinsuat', 'province_id' => 44],
			['name' => 'Datu Hoffer Ampatuan', 'province_id' => 44],
			['name' => 'Datu Montawal', 'province_id' => 44],
			['name' => 'Datu Odin Sinsuat', 'province_id' => 44],
			['name' => 'Datu Paglas', 'province_id' => 44],
			['name' => 'Datu Piang', 'province_id' => 44],
			['name' => 'Datu Salibo', 'province_id' => 44],
			['name' => 'Datu Saudi-Ampatuan', 'province_id' => 44],
			['name' => 'Datu Unsay', 'province_id' => 44],
			['name' => 'General Salipada K. Pendatun', 'province_id' => 44],
			['name' => 'Guindulungan', 'province_id' => 44],
			['name' => 'Kabuntalan', 'province_id' => 44],
			['name' => 'Mamasapano', 'province_id' => 44],
			['name' => 'Mangudadatu', 'province_id' => 44],
			['name' => 'Matanog', 'province_id' => 44],
			['name' => 'Northern Kabuntalan', 'province_id' => 44],
			['name' => 'Pagalungan', 'province_id' => 44],
			['name' => 'Paglat', 'province_id' => 44],
			['name' => 'Pandag', 'province_id' => 44],
			['name' => 'Parang', 'province_id' => 44],
			['name' => 'Rajah Buayan', 'province_id' => 44],
			['name' => 'Shariff Aguak', 'province_id' => 44],
			['name' => 'Shariff Saydona Mustapha', 'province_id' => 44],
			['name' => 'South Upi', 'province_id' => 44],
			['name' => 'Sultan Kudarat', 'province_id' => 44],
			['name' => 'Sultan Mastura', 'province_id' => 44],
			['name' => 'Sultan sa Barongis', 'province_id' => 44],
			['name' => 'Talayan', 'province_id' => 44],
			['name' => 'Talitay', 'province_id' => 44],
			['name' => 'Upi', 'province_id' => 44],
			['name' => 'Boac', 'province_id' => 45],
			['name' => 'Buenavista', 'province_id' => 45],
			['name' => 'Gasan', 'province_id' => 45],
			['name' => 'Mogpog', 'province_id' => 45],
			['name' => 'Santa Cruz', 'province_id' => 45],
			['name' => 'Torrijos', 'province_id' => 45],
			['name' => 'Masbate City', 'province_id' => 46],
			['name' => 'Aroroy', 'province_id' => 46],
			['name' => 'Baleno', 'province_id' => 46],
			['name' => 'Balud', 'province_id' => 46],
			['name' => 'Batuan', 'province_id' => 46],
			['name' => 'Cataingan', 'province_id' => 46],
			['name' => 'Cawayan', 'province_id' => 46],
			['name' => 'Claveria', 'province_id' => 46],
			['name' => 'Dimasalang', 'province_id' => 46],
			['name' => 'Esperanza', 'province_id' => 46],
			['name' => 'Mandaon', 'province_id' => 46],
			['name' => 'Milagros', 'province_id' => 46],
			['name' => 'Mobo', 'province_id' => 46],
			['name' => 'Monreal', 'province_id' => 46],
			['name' => 'Palanas', 'province_id' => 46],
			['name' => 'Pio V. Corpuz', 'province_id' => 46],
			['name' => 'Placer', 'province_id' => 46],
			['name' => 'San Fernando', 'province_id' => 46],
			['name' => 'San Jacinto', 'province_id' => 46],
			['name' => 'San Pascual', 'province_id' => 46],
			['name' => 'Uson', 'province_id' => 46],
			['name' => 'Caloocan', 'province_id' => 47],
			['name' => 'Las Piñas', 'province_id' => 47],
			['name' => 'Makati', 'province_id' => 47],
			['name' => 'Malabon', 'province_id' => 47],
			['name' => 'Mandaluyong', 'province_id' => 47],
			['name' => 'Manila', 'province_id' => 47],
			['name' => 'Marikina', 'province_id' => 47],
			['name' => 'Muntinlupa', 'province_id' => 47],
			['name' => 'Navotas', 'province_id' => 47],
			['name' => 'Parañaque', 'province_id' => 47],
			['name' => 'Pasay', 'province_id' => 47],
			['name' => 'Pasig', 'province_id' => 47],
			['name' => 'Quezon City', 'province_id' => 47],
			['name' => 'San Juan City', 'province_id' => 47],
			['name' => 'Taguig', 'province_id' => 47],
			['name' => 'Valenzuela City', 'province_id' => 47],
			['name' => 'Pateros', 'province_id' => 47],
			['name' => 'Oroquieta City', 'province_id' => 48],
			['name' => 'Ozamiz City', 'province_id' => 48],
			['name' => 'Tangub City', 'province_id' => 48],
			['name' => 'Aloran', 'province_id' => 48],
			['name' => 'Baliangao', 'province_id' => 48],
			['name' => 'Bonifacio', 'province_id' => 48],
			['name' => 'Calamba', 'province_id' => 48],
			['name' => 'Clarin', 'province_id' => 48],
			['name' => 'Concepcion', 'province_id' => 48],
			['name' => 'Don Victoriano Chiongbian', 'province_id' => 48],
			['name' => 'Jimenez', 'province_id' => 48],
			['name' => 'Lopez Jaena', 'province_id' => 48],
			['name' => 'Panaon', 'province_id' => 48],
			['name' => 'Plaridel', 'province_id' => 48],
			['name' => 'Sapang Dalaga', 'province_id' => 48],
			['name' => 'Sinacaban', 'province_id' => 48],
			['name' => 'Tudela', 'province_id' => 48],
			['name' => 'Cagayan de Oro', 'province_id' => 49],
			['name' => 'Gingoog City', 'province_id' => 49],
			['name' => 'Alubijid', 'province_id' => 49],
			['name' => 'Balingasag', 'province_id' => 49],
			['name' => 'Balingoan', 'province_id' => 49],
			['name' => 'Binuangan', 'province_id' => 49],
			['name' => 'Claveria', 'province_id' => 49],
			['name' => 'El Salvador', 'province_id' => 49],
			['name' => 'Gitagum', 'province_id' => 49],
			['name' => 'Initao', 'province_id' => 49],
			['name' => 'Jasaan', 'province_id' => 49],
			['name' => 'Kinoguitan', 'province_id' => 49],
			['name' => 'Lagonglong', 'province_id' => 49],
			['name' => 'Laguindingan', 'province_id' => 49],
			['name' => 'Libertad', 'province_id' => 49],
			['name' => 'Lugait', 'province_id' => 49],
			['name' => 'Magsaysay', 'province_id' => 49],
			['name' => 'Manticao', 'province_id' => 49],
			['name' => 'Medina', 'province_id' => 49],
			['name' => 'Naawan', 'province_id' => 49],
			['name' => 'Opol', 'province_id' => 49],
			['name' => 'Salay', 'province_id' => 49],
			['name' => 'Sugbongcogon', 'province_id' => 49],
			['name' => 'Tagoloan', 'province_id' => 49],
			['name' => 'Talisayan', 'province_id' => 49],
			['name' => 'Villanueva', 'province_id' => 49],
			['name' => 'Barlig', 'province_id' => 50],
			['name' => 'Bauko', 'province_id' => 50],
			['name' => 'Besao', 'province_id' => 50],
			['name' => 'Bontoc', 'province_id' => 50],
			['name' => 'Natonin', 'province_id' => 50],
			['name' => 'Paracelis', 'province_id' => 50],
			['name' => 'Sabangan', 'province_id' => 50],
			['name' => 'Sadanga', 'province_id' => 50],
			['name' => 'Sagada', 'province_id' => 50],
			['name' => 'Tadian', 'province_id' => 50],
			['name' => 'Bacolod City', 'province_id' => 51],
			['name' => 'Bago City', 'province_id' => 51],
			['name' => 'Cadiz City', 'province_id' => 51],
			['name' => 'Escalante City', 'province_id' => 51],
			['name' => 'Himamaylan City', 'province_id' => 51],
			['name' => 'Kabankalan City', 'province_id' => 51],
			['name' => 'La Carlota City', 'province_id' => 51],
			['name' => 'Sagay City', 'province_id' => 51],
			['name' => 'San Carlos City', 'province_id' => 51],
			['name' => 'Silay City', 'province_id' => 51],
			['name' => 'Sipalay City', 'province_id' => 51],
			['name' => 'Talisay City', 'province_id' => 51],
			['name' => 'Victorias City', 'province_id' => 51],
			['name' => 'Binalbagan', 'province_id' => 51],
			['name' => 'Calatrava', 'province_id' => 51],
			['name' => 'Candoni', 'province_id' => 51],
			['name' => 'Cauayan', 'province_id' => 51],
			['name' => 'Enrique B. Magalona', 'province_id' => 51],
			['name' => 'Hinigaran', 'province_id' => 51],
			['name' => 'Hinoba-an', 'province_id' => 51],
			['name' => 'Ilog', 'province_id' => 51],
			['name' => 'Isabela', 'province_id' => 51],
			['name' => 'La Castellana', 'province_id' => 51],
			['name' => 'Manapla', 'province_id' => 51],
			['name' => 'Moises Padilla', 'province_id' => 51],
			['name' => 'Murcia', 'province_id' => 51],
			['name' => 'Pontevedra', 'province_id' => 51],
			['name' => 'Pulupandan', 'province_id' => 51],
			['name' => 'Salvador Benedicto', 'province_id' => 51],
			['name' => 'San Enrique', 'province_id' => 51],
			['name' => 'Toboso', 'province_id' => 51],
			['name' => 'Valladolid', 'province_id' => 51],
			['name' => 'Bais City', 'province_id' => 52],
			['name' => 'Bayawan City', 'province_id' => 52],
			['name' => 'Canlaon City', 'province_id' => 52],
			['name' => 'Guihulngan City', 'province_id' => 52],
			['name' => 'Dumaguete City', 'province_id' => 52],
			['name' => 'Tanjay City', 'province_id' => 52],
			['name' => 'Amlan', 'province_id' => 52],
			['name' => 'Ayungon', 'province_id' => 52],
			['name' => 'Bacong', 'province_id' => 52],
			['name' => 'Basay', 'province_id' => 52],
			['name' => 'Bindoy', 'province_id' => 52],
			['name' => 'Dauin', 'province_id' => 52],
			['name' => 'Jimalalud', 'province_id' => 52],
			['name' => 'La Libertad', 'province_id' => 52],
			['name' => 'Mabinay', 'province_id' => 52],
			['name' => 'Manjuyod', 'province_id' => 52],
			['name' => 'Pamplona', 'province_id' => 52],
			['name' => 'San Jose', 'province_id' => 52],
			['name' => 'Santa Catalina', 'province_id' => 52],
			['name' => 'Siaton', 'province_id' => 52],
			['name' => 'Sibulan', 'province_id' => 52],
			['name' => 'Tayasan', 'province_id' => 52],
			['name' => 'Valencia', 'province_id' => 52],
			['name' => 'Vallehermoso', 'province_id' => 52],
			['name' => 'Zamboanguita', 'province_id' => 52],
			['name' => 'Allen', 'province_id' => 53],
			['name' => 'Biri', 'province_id' => 53],
			['name' => 'Bobon', 'province_id' => 53],
			['name' => 'Capul', 'province_id' => 53],
			['name' => 'Catarman', 'province_id' => 53],
			['name' => 'Catubig', 'province_id' => 53],
			['name' => 'Gamay', 'province_id' => 53],
			['name' => 'Laoang', 'province_id' => 53],
			['name' => 'Lapinig', 'province_id' => 53],
			['name' => 'Las Navas', 'province_id' => 53],
			['name' => 'Lavezares', 'province_id' => 53],
			['name' => 'Lope de Vega', 'province_id' => 53],
			['name' => 'Mapanas', 'province_id' => 53],
			['name' => 'Mondragon', 'province_id' => 53],
			['name' => 'Palapag', 'province_id' => 53],
			['name' => 'Pambujan', 'province_id' => 53],
			['name' => 'Rosario', 'province_id' => 53],
			['name' => 'San Antonio', 'province_id' => 53],
			['name' => 'San Isidro', 'province_id' => 53],
			['name' => 'San Jose', 'province_id' => 53],
			['name' => 'San Roque', 'province_id' => 53],
			['name' => 'San Vicente', 'province_id' => 53],
			['name' => 'Silvino Lobos', 'province_id' => 53],
			['name' => 'Victoria', 'province_id' => 53],
			['name' => 'Cabanatuan City', 'province_id' => 54],
			['name' => 'Gapan City', 'province_id' => 54],
			['name' => 'Science City of Muñoz', 'province_id' => 54],
			['name' => 'Palayan City', 'province_id' => 54],
			['name' => 'San Jose City', 'province_id' => 54],
			['name' => 'Aliaga', 'province_id' => 54],
			['name' => 'Bongabon', 'province_id' => 54],
			['name' => 'Cabiao', 'province_id' => 54],
			['name' => 'Carranglan', 'province_id' => 54],
			['name' => 'Cuyapo', 'province_id' => 54],
			['name' => 'Gabaldon', 'province_id' => 54],
			['name' => 'General Mamerto Natividad', 'province_id' => 54],
			['name' => 'General Tinio', 'province_id' => 54],
			['name' => 'Guimba', 'province_id' => 54],
			['name' => 'Jaen', 'province_id' => 54],
			['name' => 'Laur', 'province_id' => 54],
			['name' => 'Licab', 'province_id' => 54],
			['name' => 'Llanera', 'province_id' => 54],
			['name' => 'Lupao', 'province_id' => 54],
			['name' => 'Nampicuan', 'province_id' => 54],
			['name' => 'Pantabangan', 'province_id' => 54],
			['name' => 'Peñaranda', 'province_id' => 54],
			['name' => 'Quezon', 'province_id' => 54],
			['name' => 'Rizal', 'province_id' => 54],
			['name' => 'San Antonio', 'province_id' => 54],
			['name' => 'San Isidro', 'province_id' => 54],
			['name' => 'San Leonardo', 'province_id' => 54],
			['name' => 'Santa Rosa', 'province_id' => 54],
			['name' => 'Santo Domingo', 'province_id' => 54],
			['name' => 'Talavera', 'province_id' => 54],
			['name' => 'Talugtug', 'province_id' => 54],
			['name' => 'Zaragoza', 'province_id' => 54],
			['name' => 'Alfonso Castaneda', 'province_id' => 55],
			['name' => 'Ambaguio', 'province_id' => 55],
			['name' => 'Aritao', 'province_id' => 55],
			['name' => 'Bagabag', 'province_id' => 55],
			['name' => 'Bambang', 'province_id' => 55],
			['name' => 'Bayombong', 'province_id' => 55],
			['name' => 'Diadi', 'province_id' => 55],
			['name' => 'Dupax del Norte', 'province_id' => 55],
			['name' => 'Dupax del Sur', 'province_id' => 55],
			['name' => 'Kasibu', 'province_id' => 55],
			['name' => 'Kayapa', 'province_id' => 55],
			['name' => 'Quezon', 'province_id' => 55],
			['name' => 'Santa Fe', 'province_id' => 55],
			['name' => 'Solano', 'province_id' => 55],
			['name' => 'Villaverde', 'province_id' => 55],
			['name' => 'Abra de Ilog', 'province_id' => 56],
			['name' => 'Calintaan', 'province_id' => 56],
			['name' => 'Looc', 'province_id' => 56],
			['name' => 'Lubang', 'province_id' => 56],
			['name' => 'Magsaysay', 'province_id' => 56],
			['name' => 'Mamburao', 'province_id' => 56],
			['name' => 'Paluan', 'province_id' => 56],
			['name' => 'Rizal', 'province_id' => 56],
			['name' => 'Sablayan', 'province_id' => 56],
			['name' => 'San Jose', 'province_id' => 56],
			['name' => 'Santa Cruz', 'province_id' => 56],
			['name' => 'Calapan City', 'province_id' => 57],
			['name' => 'Baco', 'province_id' => 57],
			['name' => 'Bansud', 'province_id' => 57],
			['name' => 'Bongabong', 'province_id' => 57],
			['name' => 'Bulalacao', 'province_id' => 57],
			['name' => 'Gloria', 'province_id' => 57],
			['name' => 'Mansalay', 'province_id' => 57],
			['name' => 'Naujan', 'province_id' => 57],
			['name' => 'Pinamalayan', 'province_id' => 57],
			['name' => 'Pola', 'province_id' => 57],
			['name' => 'Puerto Galera', 'province_id' => 57],
			['name' => 'Roxas', 'province_id' => 57],
			['name' => 'San Teodoro', 'province_id' => 57],
			['name' => 'Socorro', 'province_id' => 57],
			['name' => 'Victoria', 'province_id' => 57],
			['name' => 'Puerto Princesa City', 'province_id' => 58],
			['name' => 'Aborlan', 'province_id' => 58],
			['name' => 'Agutaya', 'province_id' => 58],
			['name' => 'Araceli', 'province_id' => 58],
			['name' => 'Balabac', 'province_id' => 58],
			['name' => 'Bataraza', 'province_id' => 58],
			['name' => 'Brooke\'s Point', 'province_id' => 58],
			['name' => 'Busuanga', 'province_id' => 58],
			['name' => 'Cagayancillo', 'province_id' => 58],
			['name' => 'Coron', 'province_id' => 58],
			['name' => 'Culion', 'province_id' => 58],
			['name' => 'Cuyo', 'province_id' => 58],
			['name' => 'Dumaran', 'province_id' => 58],
			['name' => 'El Nido', 'province_id' => 58],
			['name' => 'Kalayaan', 'province_id' => 58],
			['name' => 'Linapacan', 'province_id' => 58],
			['name' => 'Magsaysay', 'province_id' => 58],
			['name' => 'Narra', 'province_id' => 58],
			['name' => 'Quezon', 'province_id' => 58],
			['name' => 'Rizal', 'province_id' => 58],
			['name' => 'Roxas', 'province_id' => 58],
			['name' => 'San Vicente', 'province_id' => 58],
			['name' => 'Sofronio Española', 'province_id' => 58],
			['name' => 'Taytay', 'province_id' => 58],
			['name' => 'Angeles City', 'province_id' => 59],
			['name' => 'City of San Fernando', 'province_id' => 59],
			['name' => 'Apalit', 'province_id' => 59],
			['name' => 'Arayat', 'province_id' => 59],
			['name' => 'Bacolor', 'province_id' => 59],
			['name' => 'Candaba', 'province_id' => 59],
			['name' => 'Floridablanca', 'province_id' => 59],
			['name' => 'Guagua', 'province_id' => 59],
			['name' => 'Lubao', 'province_id' => 59],
			['name' => 'Mabalacat', 'province_id' => 59],
			['name' => 'Macabebe', 'province_id' => 59],
			['name' => 'Magalang', 'province_id' => 59],
			['name' => 'Masantol', 'province_id' => 59],
			['name' => 'Mexico', 'province_id' => 59],
			['name' => 'Minalin', 'province_id' => 59],
			['name' => 'Porac', 'province_id' => 59],
			['name' => 'San Luis', 'province_id' => 59],
			['name' => 'San Simon', 'province_id' => 59],
			['name' => 'Santa Ana', 'province_id' => 59],
			['name' => 'Santa Rita', 'province_id' => 59],
			['name' => 'Santo Tomas', 'province_id' => 59],
			['name' => 'Sasmuan', 'province_id' => 59],
			['name' => 'Alaminos City', 'province_id' => 60],
			['name' => 'Dagupan City', 'province_id' => 60],
			['name' => 'San Carlos City', 'province_id' => 60],
			['name' => 'Urdaneta City', 'province_id' => 60],
			['name' => 'Agno', 'province_id' => 60],
			['name' => 'Aguilar', 'province_id' => 60],
			['name' => 'Alcala', 'province_id' => 60],
			['name' => 'Anda', 'province_id' => 60],
			['name' => 'Asingan', 'province_id' => 60],
			['name' => 'Balungao', 'province_id' => 60],
			['name' => 'Bani', 'province_id' => 60],
			['name' => 'Basista', 'province_id' => 60],
			['name' => 'Bautista', 'province_id' => 60],
			['name' => 'Bayambang', 'province_id' => 60],
			['name' => 'Binalonan', 'province_id' => 60],
			['name' => 'Binmaley', 'province_id' => 60],
			['name' => 'Bolinao', 'province_id' => 60],
			['name' => 'Bugallon', 'province_id' => 60],
			['name' => 'Burgos', 'province_id' => 60],
			['name' => 'Calasiao', 'province_id' => 60],
			['name' => 'Dasol', 'province_id' => 60],
			['name' => 'Infanta', 'province_id' => 60],
			['name' => 'Labrador', 'province_id' => 60],
			['name' => 'Laoac', 'province_id' => 60],
			['name' => 'Lingayen', 'province_id' => 60],
			['name' => 'Mabini', 'province_id' => 60],
			['name' => 'Malasiqui', 'province_id' => 60],
			['name' => 'Manaoag', 'province_id' => 60],
			['name' => 'Mangaldan', 'province_id' => 60],
			['name' => 'Mangatarem', 'province_id' => 60],
			['name' => 'Mapandan', 'province_id' => 60],
			['name' => 'Natividad', 'province_id' => 60],
			['name' => 'Pozzorubio', 'province_id' => 60],
			['name' => 'Rosales', 'province_id' => 60],
			['name' => 'San Fabian', 'province_id' => 60],
			['name' => 'San Jacinto', 'province_id' => 60],
			['name' => 'San Manuel', 'province_id' => 60],
			['name' => 'San Nicolas', 'province_id' => 60],
			['name' => 'San Quintin', 'province_id' => 60],
			['name' => 'Santa Barbara', 'province_id' => 60],
			['name' => 'Santa Maria', 'province_id' => 60],
			['name' => 'Santo Tomas', 'province_id' => 60],
			['name' => 'Sison', 'province_id' => 60],
			['name' => 'Sual', 'province_id' => 60],
			['name' => 'Tayug', 'province_id' => 60],
			['name' => 'Umingan', 'province_id' => 60],
			['name' => 'Urbiztondo', 'province_id' => 60],
			['name' => 'Villasis', 'province_id' => 60],
			['name' => 'Lucena City', 'province_id' => 61],
			['name' => 'Tayabas City', 'province_id' => 61],
			['name' => 'Agdangan', 'province_id' => 61],
			['name' => 'Alabat', 'province_id' => 61],
			['name' => 'Atimonan', 'province_id' => 61],
			['name' => 'Buenavista', 'province_id' => 61],
			['name' => 'Burdeos', 'province_id' => 61],
			['name' => 'Calauag', 'province_id' => 61],
			['name' => 'Candelaria', 'province_id' => 61],
			['name' => 'Catanauan', 'province_id' => 61],
			['name' => 'Dolores', 'province_id' => 61],
			['name' => 'General Luna', 'province_id' => 61],
			['name' => 'General Nakar', 'province_id' => 61],
			['name' => 'Guinayangan', 'province_id' => 61],
			['name' => 'Gumaca', 'province_id' => 61],
			['name' => 'Infanta', 'province_id' => 61],
			['name' => 'Jomalig', 'province_id' => 61],
			['name' => 'Lopez', 'province_id' => 61],
			['name' => 'Lucban', 'province_id' => 61],
			['name' => 'Macalelon', 'province_id' => 61],
			['name' => 'Mauban', 'province_id' => 61],
			['name' => 'Mulanay', 'province_id' => 61],
			['name' => 'Padre Burgos', 'province_id' => 61],
			['name' => 'Pagbilao', 'province_id' => 61],
			['name' => 'Panukulan', 'province_id' => 61],
			['name' => 'Patnanungan', 'province_id' => 61],
			['name' => 'Perez', 'province_id' => 61],
			['name' => 'Pitogo', 'province_id' => 61],
			['name' => 'Plaridel', 'province_id' => 61],
			['name' => 'Polillo', 'province_id' => 61],
			['name' => 'Quezon', 'province_id' => 61],
			['name' => 'Real', 'province_id' => 61],
			['name' => 'Sampaloc', 'province_id' => 61],
			['name' => 'San Andres', 'province_id' => 61],
			['name' => 'San Antonio', 'province_id' => 61],
			['name' => 'San Francisco', 'province_id' => 61],
			['name' => 'San Narciso', 'province_id' => 61],
			['name' => 'Sariaya', 'province_id' => 61],
			['name' => 'Tagkawayan', 'province_id' => 61],
			['name' => 'Tiaong', 'province_id' => 61],
			['name' => 'Unisan', 'province_id' => 61],
			['name' => 'Aglipay', 'province_id' => 62],
			['name' => 'Cabarroguis', 'province_id' => 62],
			['name' => 'Diffun', 'province_id' => 62],
			['name' => 'Maddela', 'province_id' => 62],
			['name' => 'Nagtipunan', 'province_id' => 62],
			['name' => 'Saguday', 'province_id' => 62],
			['name' => 'Antipolo City', 'province_id' => 63],
			['name' => 'Angono', 'province_id' => 63],
			['name' => 'Baras', 'province_id' => 63],
			['name' => 'Binangonan', 'province_id' => 63],
			['name' => 'Cainta', 'province_id' => 63],
			['name' => 'Cardona', 'province_id' => 63],
			['name' => 'Jalajala', 'province_id' => 63],
			['name' => 'Morong', 'province_id' => 63],
			['name' => 'Pililla', 'province_id' => 63],
			['name' => 'Rodriguez', 'province_id' => 63],
			['name' => 'San Mateo', 'province_id' => 63],
			['name' => 'Tanay', 'province_id' => 63],
			['name' => 'Taytay', 'province_id' => 63],
			['name' => 'Teresa', 'province_id' => 63],
			['name' => 'Alcantara', 'province_id' => 64],
			['name' => 'Banton', 'province_id' => 64],
			['name' => 'Cajidiocan', 'province_id' => 64],
			['name' => 'Calatrava', 'province_id' => 64],
			['name' => 'Concepcion', 'province_id' => 64],
			['name' => 'Corcuera', 'province_id' => 64],
			['name' => 'Ferrol', 'province_id' => 64],
			['name' => 'Looc', 'province_id' => 64],
			['name' => 'Magdiwang', 'province_id' => 64],
			['name' => 'Odiongan', 'province_id' => 64],
			['name' => 'Romblon', 'province_id' => 64],
			['name' => 'San Agustin', 'province_id' => 64],
			['name' => 'San Andres', 'province_id' => 64],
			['name' => 'San Fernando', 'province_id' => 64],
			['name' => 'San Jose', 'province_id' => 64],
			['name' => 'Santa Fe', 'province_id' => 64],
			['name' => 'Santa Maria', 'province_id' => 64],
			['name' => 'Calbayog City', 'province_id' => 65],
			['name' => 'Catbalogan City', 'province_id' => 65],
			['name' => 'Almagro', 'province_id' => 65],
			['name' => 'Basey', 'province_id' => 65],
			['name' => 'Calbiga', 'province_id' => 65],
			['name' => 'Daram', 'province_id' => 65],
			['name' => 'Gandara', 'province_id' => 65],
			['name' => 'Hinabangan', 'province_id' => 65],
			['name' => 'Jiabong', 'province_id' => 65],
			['name' => 'Marabut', 'province_id' => 65],
			['name' => 'Matuguinao', 'province_id' => 65],
			['name' => 'Motiong', 'province_id' => 65],
			['name' => 'Pagsanghan', 'province_id' => 65],
			['name' => 'Paranas', 'province_id' => 65],
			['name' => 'Pinabacdao', 'province_id' => 65],
			['name' => 'San Jorge', 'province_id' => 65],
			['name' => 'San Jose De Buan', 'province_id' => 65],
			['name' => 'San Sebastian', 'province_id' => 65],
			['name' => 'Santa Margarita', 'province_id' => 65],
			['name' => 'Santa Rita', 'province_id' => 65],
			['name' => 'Santo Niño', 'province_id' => 65],
			['name' => 'Tagapul-an', 'province_id' => 65],
			['name' => 'Talalora', 'province_id' => 65],
			['name' => 'Tarangnan', 'province_id' => 65],
			['name' => 'Villareal', 'province_id' => 65],
			['name' => 'Zumarraga', 'province_id' => 65],
			['name' => 'Alabel', 'province_id' => 66],
			['name' => 'Glan', 'province_id' => 66],
			['name' => 'Kiamba', 'province_id' => 66],
			['name' => 'Maasim', 'province_id' => 66],
			['name' => 'Maitum', 'province_id' => 66],
			['name' => 'Malapatan', 'province_id' => 66],
			['name' => 'Malungon', 'province_id' => 66],
			['name' => 'Enrique Villanueva', 'province_id' => 67],
			['name' => 'Larena', 'province_id' => 67],
			['name' => 'Lazi', 'province_id' => 67],
			['name' => 'Maria', 'province_id' => 67],
			['name' => 'San Juan', 'province_id' => 67],
			['name' => 'Siquijor', 'province_id' => 67],
			['name' => 'Sorsogon City', 'province_id' => 68],
			['name' => 'Barcelona', 'province_id' => 68],
			['name' => 'Bulan', 'province_id' => 68],
			['name' => 'Bulusan', 'province_id' => 68],
			['name' => 'Casiguran', 'province_id' => 68],
			['name' => 'Castilla', 'province_id' => 68],
			['name' => 'Donsol', 'province_id' => 68],
			['name' => 'Gubat', 'province_id' => 68],
			['name' => 'Irosin', 'province_id' => 68],
			['name' => 'Juban', 'province_id' => 68],
			['name' => 'Magallanes', 'province_id' => 68],
			['name' => 'Matnog', 'province_id' => 68],
			['name' => 'Pilar', 'province_id' => 68],
			['name' => 'Prieto Diaz', 'province_id' => 68],
			['name' => 'Santa Magdalena', 'province_id' => 68],
			['name' => 'General Santos City', 'province_id' => 69],
			['name' => 'Koronadal City', 'province_id' => 69],
			['name' => 'Banga', 'province_id' => 69],
			['name' => 'Lake Sebu', 'province_id' => 69],
			['name' => 'Norala', 'province_id' => 69],
			['name' => 'Polomolok', 'province_id' => 69],
			['name' => 'Santo Niño', 'province_id' => 69],
			['name' => 'Surallah', 'province_id' => 69],
			['name' => 'T\'boli', 'province_id' => 69],
			['name' => 'Tampakan', 'province_id' => 69],
			['name' => 'Tantangan', 'province_id' => 69],
			['name' => 'Tupi', 'province_id' => 69],
			['name' => 'Maasin City', 'province_id' => 70],
			['name' => 'Anahawan', 'province_id' => 70],
			['name' => 'Bontoc', 'province_id' => 70],
			['name' => 'Hinunangan', 'province_id' => 70],
			['name' => 'Hinundayan', 'province_id' => 70],
			['name' => 'Libagon', 'province_id' => 70],
			['name' => 'Liloan', 'province_id' => 70],
			['name' => 'Limasawa', 'province_id' => 70],
			['name' => 'Macrohon', 'province_id' => 70],
			['name' => 'Malitbog', 'province_id' => 70],
			['name' => 'Padre Burgos', 'province_id' => 70],
			['name' => 'Pintuyan', 'province_id' => 70],
			['name' => 'Saint Bernard', 'province_id' => 70],
			['name' => 'San Francisco', 'province_id' => 70],
			['name' => 'San Juan', 'province_id' => 70],
			['name' => 'San Ricardo', 'province_id' => 70],
			['name' => 'Silago', 'province_id' => 70],
			['name' => 'Sogod', 'province_id' => 70],
			['name' => 'Tomas Oppus', 'province_id' => 70],
			['name' => 'Tacurong City', 'province_id' => 71],
			['name' => 'Bagumbayan', 'province_id' => 71],
			['name' => 'Columbio', 'province_id' => 71],
			['name' => 'Esperanza', 'province_id' => 71],
			['name' => 'Isulan', 'province_id' => 71],
			['name' => 'Kalamansig', 'province_id' => 71],
			['name' => 'Lambayong', 'province_id' => 71],
			['name' => 'Lebak', 'province_id' => 71],
			['name' => 'Lutayan', 'province_id' => 71],
			['name' => 'Palimbang', 'province_id' => 71],
			['name' => 'President Quirino', 'province_id' => 71],
			['name' => 'Senator Ninoy Aquino', 'province_id' => 71],
			['name' => 'Banguingui', 'province_id' => 72],
			['name' => 'Hadji Panglima Tahil', 'province_id' => 72],
			['name' => 'Indanan', 'province_id' => 72],
			['name' => 'Jolo', 'province_id' => 72],
			['name' => 'Kalingalan Caluang', 'province_id' => 72],
			['name' => 'Lugus', 'province_id' => 72],
			['name' => 'Luuk', 'province_id' => 72],
			['name' => 'Maimbung', 'province_id' => 72],
			['name' => 'Old Panamao', 'province_id' => 72],
			['name' => 'Omar', 'province_id' => 72],
			['name' => 'Pandami', 'province_id' => 72],
			['name' => 'Panglima Estino', 'province_id' => 72],
			['name' => 'Pangutaran', 'province_id' => 72],
			['name' => 'Parang', 'province_id' => 72],
			['name' => 'Pata', 'province_id' => 72],
			['name' => 'Patikul', 'province_id' => 72],
			['name' => 'Siasi', 'province_id' => 72],
			['name' => 'Talipao', 'province_id' => 72],
			['name' => 'Tapul', 'province_id' => 72],
			['name' => 'Surigao City', 'province_id' => 73],
			['name' => 'Alegria', 'province_id' => 73],
			['name' => 'Bacuag', 'province_id' => 73],
			['name' => 'Basilisa', 'province_id' => 73],
			['name' => 'Burgos', 'province_id' => 73],
			['name' => 'Cagdianao', 'province_id' => 73],
			['name' => 'Claver', 'province_id' => 73],
			['name' => 'Dapa', 'province_id' => 73],
			['name' => 'Del Carmen', 'province_id' => 73],
			['name' => 'Dinagat', 'province_id' => 73],
			['name' => 'General Luna', 'province_id' => 73],
			['name' => 'Gigaquit', 'province_id' => 73],
			['name' => 'Libjo', 'province_id' => 73],
			['name' => 'Loreto', 'province_id' => 73],
			['name' => 'Mainit', 'province_id' => 73],
			['name' => 'Malimono', 'province_id' => 73],
			['name' => 'Pilar', 'province_id' => 73],
			['name' => 'Placer', 'province_id' => 73],
			['name' => 'San Benito', 'province_id' => 73],
			['name' => 'San Francisco', 'province_id' => 73],
			['name' => 'San Isidro', 'province_id' => 73],
			['name' => 'San Jose', 'province_id' => 73],
			['name' => 'Santa Monica', 'province_id' => 73],
			['name' => 'Sison', 'province_id' => 73],
			['name' => 'Socorro', 'province_id' => 73],
			['name' => 'Tagana-an', 'province_id' => 73],
			['name' => 'Tubajon', 'province_id' => 73],
			['name' => 'Tubod', 'province_id' => 73],
			['name' => 'Bislig City', 'province_id' => 74],
			['name' => 'Tandag City', 'province_id' => 74],
			['name' => 'Barobo', 'province_id' => 74],
			['name' => 'Bayabas', 'province_id' => 74],
			['name' => 'Cagwait', 'province_id' => 74],
			['name' => 'Cantilan', 'province_id' => 74],
			['name' => 'Carmen', 'province_id' => 74],
			['name' => 'Carrascal', 'province_id' => 74],
			['name' => 'Cortes', 'province_id' => 74],
			['name' => 'Hinatuan', 'province_id' => 74],
			['name' => 'Lanuza', 'province_id' => 74],
			['name' => 'Lianga', 'province_id' => 74],
			['name' => 'Lingig', 'province_id' => 74],
			['name' => 'Madrid', 'province_id' => 74],
			['name' => 'Marihatag', 'province_id' => 74],
			['name' => 'San Agustin', 'province_id' => 74],
			['name' => 'San Miguel', 'province_id' => 74],
			['name' => 'Tagbina', 'province_id' => 74],
			['name' => 'Tago', 'province_id' => 74],
			['name' => 'Tarlac City', 'province_id' => 75],
			['name' => 'Anao', 'province_id' => 75],
			['name' => 'Bamban', 'province_id' => 75],
			['name' => 'Camiling', 'province_id' => 75],
			['name' => 'Capas', 'province_id' => 75],
			['name' => 'Concepcion', 'province_id' => 75],
			['name' => 'Gerona', 'province_id' => 75],
			['name' => 'La Paz', 'province_id' => 75],
			['name' => 'Mayantoc', 'province_id' => 75],
			['name' => 'Moncada', 'province_id' => 75],
			['name' => 'Paniqui', 'province_id' => 75],
			['name' => 'Pura', 'province_id' => 75],
			['name' => 'Ramos', 'province_id' => 75],
			['name' => 'San Clemente', 'province_id' => 75],
			['name' => 'San Jose', 'province_id' => 75],
			['name' => 'San Manuel', 'province_id' => 75],
			['name' => 'Santa Ignacia', 'province_id' => 75],
			['name' => 'Victoria', 'province_id' => 75],
			['name' => 'Bongao', 'province_id' => 76],
			['name' => 'Languyan', 'province_id' => 76],
			['name' => 'Mapun', 'province_id' => 76],
			['name' => 'Panglima Sugala', 'province_id' => 76],
			['name' => 'Sapa-Sapa', 'province_id' => 76],
			['name' => 'Sibutu', 'province_id' => 76],
			['name' => 'Simunul', 'province_id' => 76],
			['name' => 'Sitangkai', 'province_id' => 76],
			['name' => 'South Ubian', 'province_id' => 76],
			['name' => 'Tandubas', 'province_id' => 76],
			['name' => 'Turtle Islands', 'province_id' => 76],
			['name' => 'Olongapo City', 'province_id' => 77],
			['name' => 'Botolan', 'province_id' => 77],
			['name' => 'Cabangan', 'province_id' => 77],
			['name' => 'Candelaria', 'province_id' => 77],
			['name' => 'Castillejos', 'province_id' => 77],
			['name' => 'Iba', 'province_id' => 77],
			['name' => 'Masinloc', 'province_id' => 77],
			['name' => 'Palauig', 'province_id' => 77],
			['name' => 'San Antonio', 'province_id' => 77],
			['name' => 'San Felipe', 'province_id' => 77],
			['name' => 'San Marcelino', 'province_id' => 77],
			['name' => 'San Narciso', 'province_id' => 77],
			['name' => 'Santa Cruz', 'province_id' => 77],
			['name' => 'Subic', 'province_id' => 77],
			['name' => 'Dapitan City', 'province_id' => 78],
			['name' => 'Dipolog City', 'province_id' => 78],
			['name' => 'Bacungan', 'province_id' => 78],
			['name' => 'Baliguian', 'province_id' => 78],
			['name' => 'Godod', 'province_id' => 78],
			['name' => 'Gutalac', 'province_id' => 78],
			['name' => 'Jose Dalman', 'province_id' => 78],
			['name' => 'Kalawit', 'province_id' => 78],
			['name' => 'Katipunan', 'province_id' => 78],
			['name' => 'La Libertad', 'province_id' => 78],
			['name' => 'Labason', 'province_id' => 78],
			['name' => 'Liloy', 'province_id' => 78],
			['name' => 'Manukan', 'province_id' => 78],
			['name' => 'Mutia', 'province_id' => 78],
			['name' => 'Piñan', 'province_id' => 78],
			['name' => 'Polanco', 'province_id' => 78],
			['name' => 'President Manuel A. Roxas', 'province_id' => 78],
			['name' => 'Rizal', 'province_id' => 78],
			['name' => 'Salug', 'province_id' => 78],
			['name' => 'Sergio Osmeña Sr.', 'province_id' => 78],
			['name' => 'Siayan', 'province_id' => 78],
			['name' => 'Sibuco', 'province_id' => 78],
			['name' => 'Sibutad', 'province_id' => 78],
			['name' => 'Sindangan', 'province_id' => 78],
			['name' => 'Siocon', 'province_id' => 78],
			['name' => 'Sirawai', 'province_id' => 78],
			['name' => 'Tampilisan', 'province_id' => 78],
			['name' => 'Pagadian City', 'province_id' => 79],
			['name' => 'Zamboanga City', 'province_id' => 79],
			['name' => 'Aurora', 'province_id' => 79],
			['name' => 'Bayog', 'province_id' => 79],
			['name' => 'Dimataling', 'province_id' => 79],
			['name' => 'Dinas', 'province_id' => 79],
			['name' => 'Dumalinao', 'province_id' => 79],
			['name' => 'Dumingag', 'province_id' => 79],
			['name' => 'Guipos', 'province_id' => 79],
			['name' => 'Josefina', 'province_id' => 79],
			['name' => 'Kumalarang', 'province_id' => 79],
			['name' => 'Labangan', 'province_id' => 79],
			['name' => 'Lakewood', 'province_id' => 79],
			['name' => 'Lapuyan', 'province_id' => 79],
			['name' => 'Mahayag', 'province_id' => 79],
			['name' => 'Margosatubig', 'province_id' => 79],
			['name' => 'Midsalip', 'province_id' => 79],
			['name' => 'Molave', 'province_id' => 79],
			['name' => 'Pitogo', 'province_id' => 79],
			['name' => 'Ramon Magsaysay', 'province_id' => 79],
			['name' => 'San Miguel', 'province_id' => 79],
			['name' => 'San Pablo', 'province_id' => 79],
			['name' => 'Sominot', 'province_id' => 79],
			['name' => 'Tabina', 'province_id' => 79],
			['name' => 'Tambulig', 'province_id' => 79],
			['name' => 'Tigbao', 'province_id' => 79],
			['name' => 'Tukuran', 'province_id' => 79],
			['name' => 'Vincenzo A. Sagun', 'province_id' => 79],
			['name' => 'Alicia', 'province_id' => 80],
			['name' => 'Buug', 'province_id' => 80],
			['name' => 'Diplahan', 'province_id' => 80],
			['name' => 'Imelda', 'province_id' => 80],
			['name' => 'Ipil', 'province_id' => 80],
			['name' => 'Kabasalan', 'province_id' => 80],
			['name' => 'Mabuhay', 'province_id' => 80],
			['name' => 'Malangas', 'province_id' => 80],
			['name' => 'Naga', 'province_id' => 80],
			['name' => 'Olutanga', 'province_id' => 80],
			['name' => 'Payao', 'province_id' => 80],
			['name' => 'Roseller Lim', 'province_id' => 80],
			['name' => 'Siay', 'province_id' => 80],
			['name' => 'Talusan', 'province_id' => 80],
			['name' => 'Titay', 'province_id' => 80],
			['name' => 'Tungawan', 'province_id' => 80]
        ]);
    }
}
